{{- if .Values.appSecret.create -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ default (printf "%s-secret" (include "payservice.fullname" .)) .Values.appSecret.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "payservice.labels" . | nindent 4 }}
spec:
  encryptedData: {{- with .Values.appSecret.encryptedData }}
    {{- toYaml . | nindent 4 }}
    {{- else }}
    {}
    {{- end }}
  template:
    metadata:
      name: {{ default (printf "%s-secret" (include "payservice.fullname" .)) .Values.appSecret.name }}
      namespace: {{ .Values.namespace }}
      labels:
        {{- include "payservice.labels" . | nindent 8 }}
        {{- with .Values.appSecret.extraLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations: {{- with .Values.appSecret.extraAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- else }}
        {}
        {{- end }}
    data: {{- with .Values.appSecret.data }}
      {{- toYaml . | nindent 6 }}
      {{- else }}
      {}
      {{- end }}
    type: Opaque
{{- end }}
