{{- if .Values.appSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-secret" (include "payservice.fullname" .)) .Values.appSecret.name }}
  labels:
    {{- include "payservice.labels" . | nindent 4 }}
    {{- with .Values.appSecret.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.appSecret.extraAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- with .Values.appSecret.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
