{{- if .Values.service.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ default (include "payservice.fullname" .) .Values.service.name }}
  labels:
    {{- include "payservice.labels" . | nindent 4 }}
    {{- with .Values.service.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.extraAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "payservice.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.service.http.port }}
      protocol: TCP
    - name: prom
      port: {{ .Values.service.prom.port }}
      targetPort: {{ .Values.service.prom.port }}
      protocol: TCP
    {{- with .Values.service.additionalPorts }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
