app:
  name: appName

# Uses SealedSecret. All data must be encrypted with Kubeseal or Webseal
appSecret:
  create: true
  encryptedData: {}

container:
  image:
    name: "" # Set to dev image name
  config:
    consul:
      kv_prefix: ""
    otel:
      endpoint: ""
      tracesSampler: "parentbased_always_off"
    profiler:
      projectName: ""
      zone: ""
  envMounts: # Usually (but not automatically) set to appname-secret & appname-configmap
    secret: ""
    appConfig: ""
